version: 2.1

# Define the jobs we want to run for this project
jobs:
  # build:
  #   docker:
  #   - image: cimg/node
  #     auth:
  #         username: mydockerhub-user
  #         password: $DOCKERHUB_PASSWORD  
  #   steps:
  #     - checkout
  #     - run: node --version
  #     - run: echo "this is the build job"
  build:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: node --version

  install:
    docker:
      - image: cimg/node:17.4.0 
    steps:
      - checkout
      - run: ls
      - run: npm install
      - run: npm ci
      - run: npm install --save-dev expo-cli
      - run: expo --version


# Orchestrate our job run sequence
workflows:
  build_and_install:
    jobs:
      - build
      - install

      